Repository mark3labs/mcp-go, pull requests merged in 2025-05, with the labels that each got.

#268 docs: make code examples in the README correct as per spec
  README.md
Labels: documentation

#269 docs: Remove reference to `mcp.RoleSystem`
  README.md
Labels: documentation

#246 Optimization of listByPagination Performance
  mcp/prompts.go
  mcp/tools.go
  mcp/types.go
  server/server.go
  server/server_test.go
Labels: Needs Submitter Response

#281 chore: add issue and pull request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/documentation-improvement.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull_request_template.md
Labels: documentation

#284 fix(docs): Update README link
  README.md
Labels: documentation

#289 fix(session): Don't send tool changed notifications if session not initialized yet
  server/session.go
  server/session_test.go
Labels: bug

#287 refactor: make CallToolRequest.Arguments more flexible (Breaking Change)
  README.md
  client/inprocess_test.go
  client/sse_test.go
  examples/custom_context/main.go
  examples/dynamic_path/main.go
  examples/everything/main.go
  examples/typed_tools/main.go
  mcp/tools.go
  mcp/tools_test.go
  mcp/typed_tools.go
  mcp/typed_tools_test.go
  mcp/utils.go
  mcptest/mcptest_test.go
Labels: type: enhancement, area: sdk

#273 Feat: Impl Server-Side Streamable HTTP transport
  README.md
  client/transport/streamable_http.go
  examples/custom_context/main.go
  examples/everything/main.go
  examples/simple_client/main.go
  mcp/types.go
  server/http_transport_options.go
  server/sse.go
  server/sse_test.go
  server/streamable_http.go
  server/streamable_http_test.go
  util/logger.go
Labels: type: enhancement, area: mcp spec

#296 feat: Implement OAuth in the client
  client/oauth.go
  client/oauth_test.go
  client/transport/oauth.go
  client/transport/oauth_test.go
  client/transport/oauth_utils.go
  client/transport/oauth_utils_test.go
  client/transport/streamable_http.go
  client/transport/streamable_http_oauth_test.go
  examples/oauth_client/README.md
  examples/oauth_client/main.go
Labels: type: enhancement, area: mcp spec
