Repository mark3labs/mcp-go, pull requests merged in 2025-09, with the labels that each got.

#545 Remove useless allocations; use (*Type)(nil) instead
  mcp/utils.go
Labels: type: bug

#539 Detect Pong from MCP Client and skip Session ID validation
  server/streamable_http.go
  server/streamable_http_test.go
Labels: type: bug

#581 fix(oauth): use oauth-authorization-server discovery before default endpoints
  client/transport/oauth.go
  client/transport/oauth_test.go
Labels: type: bug, status: needs submitter response

#547 feat: add support for call tool result annotations
  mcp/utils.go
  mcp/utils_test.go
Labels: type: enhancement
